### ISSUE TITLE
Unable to record keys on Kobo Aura H20

### ISSUE THREAD

**Issue by sandrotavares** [sublipri/kobo-wifi-remote#5] opened 2024-04-08 19:52 UTC
Device KOBO Aura H2O (1st version)

Can generate screenshot, however cannot generate log "Error: No such file or directory (os error 2)"

Tried on Firefox (android/mac) and Chrome (mac).

During the setup when trying to configure the keys it doesn't give me the 5 seconds and immediately states "error no input detected"

**Comment by sublipri** [comment] 2024-04-09 01:05
Thanks for the report!

That's a pity the log download isn't working. It's hard to tell exactly what the problem is without one. If you can try installing [version 0.1.1](https://github.com/sublipri/kobo-wifi-remote/releases/tag/v0.1.1) that might work, since 0.2.0 was a major re-write. A log file from 0.1.1 would be useful if it does work, as would the output from the input check done during setup.

That might be broken too though if there's some quirk about the H20 I haven't accounted for. I'll do some research and also try to improve some of the error messages to be more useful. 

If 0.1.1 is broken and you have shell access to the Kobo (Telnet via enabling devmode or SSH via [this package](https://www.mobileread.com/forums/showthread.php?t=254214)), I can provide some commands to run that might be helpful too.

**Comment by sandrotavares** [comment] 2024-04-09 17:01
Hey 0.1.1 worked =D

I'm attaching the log 
[wifiremote-1712682051.log.gz](https://github.com/sublipri/kobo-wifi-remote/files/14921738/wifiremote-1712682051.log.gz)

**Comment by sublipri** [comment] 2024-04-10 07:31
Cool glad 0.1.1 worked!  Thanks for the log. I'm still not exactly sure what the problem is, but I've made a few changes that might help with the logging and recording. If you're able to test the build I've attached and let me know whether it improves anything I'd appreciate it.
 
 [KoboWiFiRemote-0.2.0-H20-test.zip](https://github.com/sublipri/kobo-wifi-remote/files/14928983/KoboWiFiRemote-0.2.0-H20-test.zip)
 
 And if the logging does work please attach a new log file even if the recording works too

**Comment by sandrotavares** [comment] 2024-04-10 17:54
Hey,

The modal doesn't close automatically when i'm trying to tap the device, but i think no input gets recorded because the 5 seconds end and when i go to the page turner nothing happens.

Clicking the troubleshooting page gives me a timeout so i'm unable to generate a log to send you...

**Comment by sandrotavares** [comment] 2024-04-10 17:58
So... I don't think its working right now...

Clicking the buttons during the configuration is opening a new window on the browser where nothing happens.

with urls like "http://xxx.xxx.xx.xx/cgi-bin/record-input.cgi?path-segment=right&display-name=Next&sort-value=%00&keyboard-shortcut=ArrowRight"

Here's the log file either way
[wifiremote-1712771785.log.gz](https://github.com/sublipri/kobo-wifi-remote/files/14935957/wifiremote-1712771785.log.gz)

**Comment by sublipri** [comment] 2024-04-10 21:32
Hmm that URL is from version 0.1.1. I think your browser might be caching the old page. Try clearing the cache by forcing a refresh or opening it in a new incognito/private window.

That log file is from the new version so that's working now at least! If you can get a log after doing the configuration that should help.

**Comment by sandrotavares** [comment] 2024-04-12 16:47
You were right it was caching the page.

However clicking to record the inputs still goes the 5 seconds without detecting the input from Kobo

New log:

[wifiremote-1712940325.log.gz](https://github.com/sublipri/kobo-wifi-remote/files/14961342/wifiremote-1712940325.log.gz)

**Comment by sublipri** [comment] 2024-04-15 05:14
Okay thanks I think I can see what the problem is. This build should hopefully work. If it does work please attach another log to help me confirm a couple of things before I release a version with a proper fix. If it still doesn't work, try recording a custom action after unchecking the advanced options "Only Check Touchscreen" and "Optimize Input" and see if that makes a difference.

[KoboWiFiRemote-0.2.0-H20-record-fix.zip](https://github.com/sublipri/kobo-wifi-remote/files/14974237/KoboWiFiRemote-0.2.0-H20-record-fix.zip)

**Comment by sandrotavares** [comment] 2024-04-15 19:25
Hey, it did work.

Here's the log:
[wifiremote-1713209055.log.gz](https://github.com/sublipri/kobo-wifi-remote/files/14983482/wifiremote-1713209055.log.gz)

**Comment by sublipri** [comment] 2024-04-16 03:55
Great! Thanks for testing :)

**Comment by sublipri** [comment] 2024-07-15 05:41
Should be fixed in [0.3.0](https://github.com/sublipri/kobo-wifi-remote/releases/tag/v0.3.0)

**Closed as completed by sublipri** 2024-07-15 05:41 UTC
Labels: bug
